### PR TITLE
Merge Carbon 5 Multitenancy Feature to Master Branch

### PR DESCRIPTION
**Pull request by imesh**
This pull request merges Carbon 5 Multitenancy feature implemented in move-to-c5 branch to master branch.  It was initially implemented by @lasanthaS and few refinements were done afterwards.

### CODE REVIEW

**Comment by imesh** [comment]
Please hold this pull request until API security features are finalized.

**Comment by imesh** [comment]
API security interceptors have been added in PR https://github.com/wso2/carbon-multitenancy/pull/120, please review and merge.

**Comment by Niranjan-K** [comment]
@imesh : Is this PR required? If so, please resolve the conflicts inorder for us to merge the PR.

**Comment by Kishanthan** [comment]
@imesh , there are too many conflicts and move-to-c5 branch is totally different from master(which is still on C4). Please fix this PR or create another PR from the move-to-c5 branch. Alternatively, we can make move-to-c5 as the master, if it is the active development branch.

**Comment by Kishanthan** [comment]
Closing this since there are too many conflicts and move-to-c5 branch is totally different from master(which is still on C4). Please fix this PR or create another PR from the move-to-c5 branch. Alternatively, we can make move-to-c5 as the master, if it is the active development branch.

**Pull request closed without merging**
